version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ridwanda
      POSTGRES_PASSWORD: ridwanda
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ridwanda@rapidtech.id
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"